config/routes.rb
Docent::Engine.routes.draw do
  resources :links

  root to: 'links#index'
end

app/models/docent/link.rb
module Docent
  class Link < ActiveRecord::Base
    attr_accessible :action, :controller, :url

    def shortcut
      "#{controller}##{action}"
    end

    def self.link_for(controller=nil, action=nil)
      if (links = self.where(controller: controller).
                  where(self.arel_table[:action].eq(action)).
                  where(self.arel_table[:action].not_eq(''))).length > 0
        links.first.url
      elsif (links = self.where(controller: controller).
                     where(self.arel_table[:action].eq(''))).length > 0
        links.first.url
      else
        Docent.default_link
      end
    end
  end
end

app/controllers/docent/application_controller.rb
module Docent
  class ApplicationController < ActionController::Base
    before_filter :basic_authenticate, if: lambda { Docent.username and Docent.password }

    private

    def basic_authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name == Docent.username and password == Docent.password
      end
    end
  end
end

app/controllers/docent/links_controller.rb
require_dependency "docent/application_controller"

module Docent
  class LinksController < ApplicationController

    def index
      @links = Link.all
    end

    def new
      @link = Link.new
    end

    def edit
      @link = Link.find(params[:id])
    end

    def create
      @link = Link.new(params[:link])

      if @link.save
        redirect_to links_url, notice: 'Successfully created link.'
      else
        render action: "new"
      end
    end

    def update
      @link = Link.find(params[:id])

      if @link.update_attributes(params[:link])
        redirect_to links_url, notice: 'Successfully updated link.'
      else
        render action: "edit"
      end
    end

    def destroy
      @link = Link.find(params[:id])
      @link.destroy

      redirect_to links_url, notice: 'Successfully deleted link.'
    end
  end
end

app/helpers/docent/application_helper.rb
module Docent
  module ApplicationHelper
    def link_to_docent(label="Help", options={})
      link_to label, Docent::Link.link_for(controller.controller_name, controller.action_name), options
    end
  end
end

app/views/docent/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :controller %><br />
    <%= f.text_field :controller %>
  </div>
  <div class="field">
    <%= f.label :action %><br />
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :url, 'URL' %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/docent/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/docent/links/index.html.erb
<h1>Links</h1>

<%= link_to 'New Link', new_link_path, class: 'button' %>

<table>
  <tr>
    <th>controller#action</th>
    <th>URL</th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr id="link_<%= link.id %>" class="<%= cycle('odd','even') %>">
    <td><%= link_to link.shortcut, edit_link_path(link) %></td>
    <td><%= link_to link.url, link.url %></td>
    <td><%= link_to 'Delete', link, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button' %></td>
  </tr>
<% end %>
</table>

app/views/docent/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/layouts/docent/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Docent</title>
  <%= stylesheet_link_tag    "docent/application", :media => "all" %>
  <%= javascript_include_tag "docent/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1><%= link_to 'Docent', root_path %></h1>
  </header>

  <div id="content">
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </div>

  <footer>
    Powered by
    <%= link_to 'Docent', 'https://github.com/ruralocity/docent' %>
  </footer>
</body>
</html>